title: Jenna Everard
#url: "www.jennaeverard.com"
# FOR TESTING
baseurl: ""

# FOR PROD
#baseurl: "https://www.jennaeverard.com/"

markdown: kramdown
#ins_logo: "./img/favicon.png"

remote_theme: ankitsultana/researcher@gem

tracking_id: #

footer: no
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "https://www.jennaeverard.com/"
 - name: "Research"
   link: "https://www.jennaeverard.com/research"
 - name: "Field Work"
   link: "https://www.jennaeverard.com/fieldwork"
 - name: "Code"
   link: "https://www.jennaeverard.com/code"
 - name: "CV"
   link: "https://www.jennaeverard.com/cv"
